import sqlite3
import os
import datetime

# Database configuration for cloud deployment compatability
DB_NAME = os.environ.get('DB_PATH', "mock_banner.db")

def get_db_connection():
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    """Buts up the mock Banner schema in SQLite"""
    conn = get_db_connection()
    cursor = conn.cursor()

    # 1. SPRIDEN
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS SPRIDEN (
        SPRIDEN_PIDM INTEGER PRIMARY KEY AUTOINCREMENT,
        SPRIDEN_ID TEXT UNIQUE NOT NULL,
        SPRIDEN_LAST_NAME TEXT NOT NULL,
        SPRIDEN_FIRST_NAME TEXT NOT NULL,
        SPRIDEN_MI TEXT,
        SPRIDEN_CHANGE_IND TEXT,
        SPRIDEN_ENTITY_IND TEXT DEFAULT 'P',
        SPRIDEN_ACTIVITY_DATE DATE DEFAULT CURRENT_DATE
    )
    ''')

    # 2. PEBEMPL
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS PEBEMPL (
        PEBEMPL_PIDM INTEGER PRIMARY KEY,
        PEBEMPL_EMPL_STATUS TEXT NOT NULL,
        PEBEMPL_ECLS_CODE TEXT NOT NULL,
        PEBEMPL_ORG_CODE_DIST TEXT,
        PEBEMPL_FIRST_HIRE_DATE DATE NOT NULL,
        PEBEMPL_CURRENT_HIRE_DATE DATE NOT NULL,
        PEBEMPL_ADJ_SERVICE_DATE DATE,
        PEBEMPL_ACTIVITY_DATE DATE DEFAULT CURRENT_DATE,
        FOREIGN KEY (PEBEMPL_PIDM) REFERENCES SPRIDEN (SPRIDEN_PIDM)
    )
    ''')

    # 3. NBRJOBS
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS NBRJOBS (
        NBRJOBS_PIDM INTEGER NOT NULL,
        NBRJOBS_POSN TEXT NOT NULL,
        NBRJOBS_SUFF TEXT NOT NULL,
        NBRJOBS_EFFECTIVE_DATE DATE NOT NULL,
        NBRJOBS_STATUS TEXT NOT NULL,
        NBRJOBS_DESC TEXT,
        NBRJOBS_ECLS_CODE TEXT,
        NBRJOBS_CLASSIFICATION TEXT,
        NBRJOBS_JOB_CATEGORY TEXT,
        NBRJOBS_JOB_TYPE TEXT,
        NBRJOBS_LOCATION TEXT,
        NBRJOBS_WORKPLACE TEXT,
        NBRJOBS_PAY_BAND TEXT,
        NBRJOBS_ACTIVITY_DATE DATE DEFAULT CURRENT_DATE,
        PRIMARY KEY (NBRJOBS_PIDM, NBRJOBS_POSN, NBRJOBS_SUFF, NBRJOBS_EFFECTIVE_DATE),
        FOREIGN KEY (NBRJOBS_PIDM) REFERENCES PEBEMPL (PEBEMPL_PIDM)
    )
    ''')

    # 4. NTRPBND (Pay Band Rates)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS NTRPBND (
        NTRPBND_CODE TEXT PRIMARY KEY,
        NTRPBND_MIN INTEGER NOT NULL,
        NTRPBND_MAX INTEGER NOT NULL,
        NTRPBND_ACTIVITY_DATE DATE DEFAULT CURRENT_DATE
    )
    ''')

    # 5. NBRBJOB (Payroll Detail)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS NBRBJOB (
        NBRBJOB_PIDM INTEGER NOT NULL,
        NBRBJOB_POSN TEXT NOT NULL,
        NBRBJOB_SUFF TEXT NOT NULL,
        NBRBJOB_BEGIN_DATE DATE NOT NULL,
        NBRBJOB_END_DATE DATE,
        NBRBJOB_CONTRACT_TYPE TEXT,
        NBRBJOB_SALARY_ENCUMBRANCE REAL,
        NBRBJOB_HRLY_RATE REAL,
        NBRBJOB_ACTIVITY_DATE DATE DEFAULT CURRENT_DATE,
        PRIMARY KEY (NBRBJOB_PIDM, NBRBJOB_POSN, NBRBJOB_SUFF, NBRBJOB_BEGIN_DATE),
        FOREIGN KEY (NBRBJOB_PIDM, NBRBJOB_POSN, NBRBJOB_SUFF, NBRBJOB_BEGIN_DATE)
            REFERENCES NBRJOBS (NBRJOBS_PIDM, NBRJOBS_POSN, NBRJOBS_SUFF, NBRJOBS_EFFECTIVE_DATE)
    )
    ''')

    # 6. PHRPAYRO (Payroll History with Deductions)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS PHRPAYRO (
        PHRPAYRO_PIDM INTEGER NOT NULL,
        PHRPAYRO_EVENT_DATE DATE NOT NULL,
        PHRPAYRO_GROSS_PAY REAL,
        PHRPAYRO_FED_TAX REAL DEFAULT 0,
        PHRPAYRO_STATE_TAX REAL DEFAULT 0,
        PHRPAYRO_NET_PAY REAL,
        PHRPAYRO_ACTIVITY_DATE DATE DEFAULT CURRENT_DATE,
        PRIMARY KEY (PHRPAYRO_PIDM, PHRPAYRO_EVENT_DATE),
        FOREIGN KEY (PHRPAYRO_PIDM) REFERENCES SPRIDEN (SPRIDEN_PIDM)
    )
    ''')

    # 7. GURUAUD (Audit History)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS GURUAUD (
        GURUAUD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        GURUAUD_PIDM INTEGER,
        GURUAUD_ACTION TEXT NOT NULL,
        GURUAUD_USER TEXT DEFAULT 'aomchavez',
        GURUAUD_IP TEXT,
        GURUAUD_ACTIVITY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        GURUAUD_DETAILS TEXT,
        FOREIGN KEY (GURUAUD_PIDM) REFERENCES SPRIDEN (SPRIDEN_PIDM)
    )
    ''')

    conn.commit()
    conn.close()
    print("Database Initialized")

if __name__ == "__main__":
    init_db()
