-- =============================================
-- Script: hr_reporting_views.sql
-- Description: Analytics views for HR and Payroll Reporting.
-- Author: HR/Payroll Analyst
-- Date: 2026-02-03
-- =============================================

-- VIEW 1: Active Employee Headcount by Department and Class
-- Useful for dashboarding and strategic planning.
CREATE OR REPLACE VIEW HR_HEADCOUNT_V AS
SELECT 
    PEBEMPL_ORG_CODE_DIST AS DEPT_CODE,
    PEBEMPL_ECLS_CODE AS EMPLOYEE_CLASS,
    COUNT(*) AS HEADCOUNT,
    MIN(PEBEMPL_CURRENT_HIRE_DATE) AS EARLIEST_HIRE_DATE,
    MAX(PEBEMPL_CURRENT_HIRE_DATE) AS LATEST_HIRE_DATE
FROM PEBEMPL
WHERE PEBEMPL_EMPL_STATUS = 'A'
GROUP BY PEBEMPL_ORG_CODE_DIST, PEBEMPL_ECLS_CODE;

COMMENT ON TABLE HR_HEADCOUNT_V IS 'Aggregated headcount by Dept and Class';

-- VIEW 2: Payroll Expenditure Analysis
-- Joins Job and Detail tables to project payroll costs
CREATE OR REPLACE VIEW PAYROLL_EXPENDITURE_V AS
SELECT 
    j.NBRJOBS_POSN AS POSITION_NUM,
    j.NBRJOBS_DESC AS POSITION_TITLE,
    COUNT(j.NBRJOBS_PIDM) AS INCUMBENT_COUNT,
    SUM(b.NBRBJOB_SALARY_ENCUMBRANCE) AS TOTAL_SALARY_COST,
    AVG(b.NBRBJOB_SALARY_ENCUMBRANCE) AS AVG_SALARY
FROM NBRJOBS j
JOIN NBRBJOB b 
  ON j.NBRJOBS_PIDM = b.NBRBJOB_PIDM
 AND j.NBRJOBS_POSN = b.NBRBJOB_POSN
 AND j.NBRJOBS_SUFF = b.NBRBJOB_SUFF
 AND j.NBRJOBS_EFFECTIVE_DATE = b.NBRBJOB_BEGIN_DATE -- Simplified join
WHERE j.NBRJOBS_STATUS = 'A'
GROUP BY j.NBRJOBS_POSN, j.NBRJOBS_DESC;

COMMENT ON TABLE PAYROLL_EXPENDITURE_V IS 'Payroll cost analysis by Position';

-- VIEW 3: Employee Detail View (Flattened)
-- Used for ad-hoc reporting needs
CREATE OR REPLACE VIEW HR_EMPLOYEE_DETAIL_V AS
SELECT 
    s.SPRIDEN_ID,
    s.SPRIDEN_LAST_NAME || ', ' || s.SPRIDEN_FIRST_NAME AS FULL_NAME,
    p.PEBEMPL_EMPL_STATUS,
    p.PEBEMPL_ECLS_CODE,
    p.PEBEMPL_ORG_CODE_DIST,
    j.NBRJOBS_POSN,
    j.NBRJOBS_DESC,
    b.NBRBJOB_SALARY_ENCUMBRANCE
FROM SPRIDEN s
JOIN PEBEMPL p ON s.SPRIDEN_PIDM = p.PEBEMPL_PIDM
LEFT JOIN NBRJOBS j ON p.PEBEMPL_PIDM = j.NBRJOBS_PIDM AND j.NBRJOBS_STATUS = 'A'
LEFT JOIN NBRBJOB b ON j.NBRJOBS_PIDM = b.NBRBJOB_PIDM 
                   AND j.NBRJOBS_POSN = b.NBRBJOB_POSN 
                   AND j.NBRJOBS_SUFF = b.NBRBJOB_SUFF
WHERE s.SPRIDEN_CHANGE_IND IS NULL;

COMMENT ON TABLE HR_EMPLOYEE_DETAIL_V IS 'Comprehensive Employee Detail View';
